(ns empire.application.ports.movement)

(defprotocol MovementPort
  (movement-move-unit [movement coords target cell current-map] "Resolve one movement step.")
  (movement-get-active-unit [movement cell] "Get active unit in a cell for attention/input.")
  (movement-is-army-aboard-transport? [movement active-unit] "True if active unit is an army aboard transport.")
  (movement-is-fighter-from-airport? [movement active-unit] "True if active unit is airport fighter.")
  (movement-is-fighter-from-carrier? [movement active-unit] "True if active unit is carrier fighter.")
  (movement-context [movement cell active-unit] "Determine movement context for active unit.")
  (movement-set-unit-mode [movement coords mode] "Set unit mode at coords.")
  (movement-add-unit-at [movement coords unit-type owner] "Add a unit at coords for owner.")
  (movement-wake-at [movement coords] "Wake city/unit at coords.")
  (movement-set-unit-movement [movement coords target extended?] "Queue movement target for unit.")
  (movement-update-cell-visibility [movement pos owner] "Recompute visibility around pos for owner.")
  (movement-update-cell-visibility-with-unit [movement pos owner unit] "Recompute visibility at pos for owner using explicit unit.")
  (movement-find-nearest-unexplored [movement pos unit-type] "Find nearest unexplored target for the given unit type.")
  (movement-bfs-to-unseen-coast [movement pos computer-map claimed-targets] "Find path to unseen coast for patrol exploration.")
  (movement-bfs-to-land-ho-target [movement from target computer-map] "Find sea path to target coastal objective.")
  (movement-bfs-to-coast-target [movement from computer-map] "Find path to best coast target.")
  (movement-next-step [movement from target unit-type passability-fn cache-key-extra] "Compute next A* step toward target.")
  (movement-lake-cells [movement world lake-max-cells] "Classify explored small sea components as lakes."))
