;; mutation-tested: no
(ns empire.units.config)

(def army-speed 1)
(def army-cost 5)
(def army-hits 1)
(def army-strength 1)
(def army-display-char "A")
(def army-visibility-radius 1)

(def fighter-speed 8)
(def fighter-cost 10)
(def fighter-hits 1)
(def fighter-strength 1)
(def fighter-display-char "F")
(def fighter-fuel 32)
(def fighter-visibility-radius 1)
(def fighter-bingo-threshold (quot fighter-fuel 4))
(def bingo-fuel-divisor 4)
(def explore-steps 50)

(def satellite-speed 10)
(def satellite-cost 50)
(def satellite-hits 1)
(def satellite-strength 1)
(def satellite-display-char "Z")
(def satellite-turns 50)
(def satellite-visibility-radius 2)

(def transport-speed 2)
(def transport-cost 30)
(def transport-hits 1)
(def transport-strength 1)
(def transport-display-char "T")
(def transport-capacity 6)
(def transport-visibility-radius 1)

(def carrier-speed 2)
(def carrier-cost 30)
(def carrier-hits 8)
(def carrier-strength 1)
(def carrier-display-char "C")
(def carrier-capacity 8)
(def carrier-visibility-radius 1)
